/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Coaster.glb --draco --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, Gltf } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

type ActionName = 'bumper_car_export_1.001|Scene' | 'support_tall.010|Scene' | 'bumper_car_export_1.002|Scene' | 'bumper_car_export_1.003|Scene' | 'bumper_car_export_1.004|Scene' | 'bumper_car_export_1.005|Scene' | 'bumper_car_export_1.006|Scene' | 'Circle.023|Scene' | 'track_geo_curve|Scene'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    bumper_car_export_1001: THREE.Mesh
    Plane010: THREE.Mesh
    Plane010_1: THREE.Mesh
    bumper_car_export_1002: THREE.Mesh
    bumper_car_export_1003: THREE.Mesh
    bumper_car_export_1004: THREE.Mesh
    bumper_car_export_1005: THREE.Mesh
    bumper_car_export_1006: THREE.Mesh
    Circle023: THREE.Mesh
  }
  materials: {
    rollercoastercart: THREE.MeshStandardMaterial
    build_gen_1: THREE.MeshStandardMaterial
    build_gen_2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/Coaster.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="track_geo_curve" position={[-21.583, -0.921, 60.471]} rotation={[Math.PI, -1.307, Math.PI]} />
        <mesh name="bumper_car_export_1001" geometry={nodes.bumper_car_export_1001.geometry} material={materials.rollercoastercart} position={[-43.401, 3.005, 68.314]} rotation={[0.137, -0.048, -0.209]} />
        <group name="support_tall010" position={[-12.219, -2.727, -74.991]} rotation={[0, -1.278, 0]}>
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.build_gen_1} />
          <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials.build_gen_2} />
        </group>
        <mesh name="bumper_car_export_1002" geometry={nodes.bumper_car_export_1002.geometry} material={materials.rollercoastercart} position={[-43.339, 3.295, 66.256]} rotation={[0.147, -0.071, -0.251]} />
        <mesh name="bumper_car_export_1003" geometry={nodes.bumper_car_export_1003.geometry} material={materials.rollercoastercart} position={[-43.111, 3.613, 64.215]} rotation={[0.145, -0.098, -0.251]} />
        <mesh name="bumper_car_export_1004" geometry={nodes.bumper_car_export_1004.geometry} material={materials.rollercoastercart} position={[-42.876, 3.932, 62.174]} rotation={[0.142, -0.126, -0.25]} />
        <mesh name="bumper_car_export_1005" geometry={nodes.bumper_car_export_1005.geometry} material={materials.rollercoastercart} position={[-42.594, 4.228, 60.137]} rotation={[0.138, -0.149, -0.249]} />
        <mesh name="bumper_car_export_1006" geometry={nodes.bumper_car_export_1006.geometry} material={materials.rollercoastercart} position={[-42.234, 4.487, 58.105]} rotation={[0.13, -0.165, -0.249]} />
        <mesh name="Circle023" geometry={nodes.Circle023.geometry} material={materials.build_gen_1} position={[-21.583, -0.921, 60.471]} rotation={[Math.PI, -1.307, Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Coaster.glb')
